//! The Storm (MPQ) crypto primitives — byte-exact with the real client.
//!
//! Three pieces, all driven by one statically-generated 0x500-entry table:
//! - [`hash_string`] — Blizzard's string hash, used for hash-table indexing (`TABLE_OFFSET`), the two
//!   filename verifiers (`NAME_A`/`NAME_B`), and table/file keys (`FILE_KEY`).
//! - [`decrypt_block`] — the in-place table/sector decryptor.
//!
//! 1.12.1 archives carry **no encrypted files** (verified across the real `Data/`), so only the hash
//! and block *tables* are ever decrypted. The known StormLib vectors are pinned as tests below.

/// The MPQ encryption table (0x500 u32s), generated by the StormLib seed walk. `const fn` so it's
/// baked into the binary, identical to the table the client builds at runtime.
const fn encryption_table() -> [u32; 0x500] {
    let mut table = [0u32; 0x500];
    let mut seed: u32 = 0x0010_0001;
    let mut i1 = 0;
    while i1 < 0x100 {
        let mut i2 = 0;
        while i2 < 5 {
            let idx = i1 + i2 * 0x100;
            seed = (seed.wrapping_mul(125).wrapping_add(3)) % 0x2A_AAAB;
            let t1 = (seed & 0xFFFF) << 0x10;
            seed = (seed.wrapping_mul(125).wrapping_add(3)) % 0x2A_AAAB;
            let t2 = seed & 0xFFFF;
            table[idx] = t1 | t2;
            i2 += 1;
        }
        i1 += 1;
    }
    table
}

static TABLE: [u32; 0x500] = encryption_table();

/// Statically-built 256-element lookup table for character normalization.
/// Maps every `u8` byte to its normalized `u32` value (converting `/` to `\` and lowercase ASCII to uppercase).
const fn build_normalization_table() -> [u32; 256] {
    let mut table = [0u32; 256];
    let mut i = 0;
    while i < 256 {
        let b = i as u8;
        let ch = match b {
            b'/' => b'\\',
            other => {
                if other >= b'a' && other <= b'z' {
                    other - 32
                } else {
                    other
                }
            }
        };
        table[i] = ch as u32;
        i += 1;
    }
    table
}

static NORMALIZATION_TABLE: [u32; 256] = build_normalization_table();

/// Hash-type selectors (the table-quadrant offsets the client uses).
pub mod hash_type {
    /// Hash-table slot index.
    pub const TABLE_OFFSET: u32 = 0x000;
    /// Filename verifier A (stored in the hash entry).
    pub const NAME_A: u32 = 0x100;
    /// Filename verifier B (stored in the hash entry).
    pub const NAME_B: u32 = 0x200;
    /// File / table decryption key.
    pub const FILE_KEY: u32 = 0x300;
}

/// Blizzard's string hash. Normalizes `/`→`\` and ASCII-uppercases (matching the client's
/// `AsciiToUpper` table, which only folds `a`–`z`), then runs the seed mix.
/// Optimized using a pre-computed normalization lookup table to bypass branching.
pub fn hash_string(name: &str, kind: u32) -> u32 {
    let mut seed1: u32 = 0x7FED_7FED;
    let mut seed2: u32 = 0xEEEE_EEEE;
    for &b in name.as_bytes() {
        let ch = NORMALIZATION_TABLE[b as usize];
        seed1 = TABLE[(kind.wrapping_add(ch)) as usize] ^ seed1.wrapping_add(seed2);
        seed2 = ch
            .wrapping_add(seed1)
            .wrapping_add(seed2)
            .wrapping_add(seed2 << 5)
            .wrapping_add(3);
    }
    seed1
}

/// Decrypt a block of `u32`s in place with `key` (the StormLib block cipher). A zero key is a no-op,
/// as in the client. Used for the hash/block tables; file data is never encrypted in 1.12.1.
pub fn decrypt_block(data: &mut [u32], mut key: u32) {
    if key == 0 {
        return;
    }
    let mut seed: u32 = 0xEEEE_EEEE;
    for v in data.iter_mut() {
        seed = seed.wrapping_add(TABLE[0x400 + (key & 0xFF) as usize]);
        let ch = *v ^ key.wrapping_add(seed);
        *v = ch;
        key = (!key << 0x15).wrapping_add(0x1111_1111) | (key >> 0x0B);
        seed = ch
            .wrapping_add(seed)
            .wrapping_add(seed << 5)
            .wrapping_add(3);
    }
}

/// Test-only inverse of [`decrypt_block`] — lets the reader's round-trip tests (here and in `lib`)
/// build the encrypted hash/block tables a real archive stores. Same walk, XOR on the plaintext side.
#[cfg(test)]
pub(crate) fn encrypt_block(data: &mut [u32], mut key: u32) {
    let mut seed: u32 = 0xEEEE_EEEE;
    for v in data.iter_mut() {
        seed = seed.wrapping_add(TABLE[0x400 + (key & 0xFF) as usize]);
        let plain = *v;
        *v = plain ^ key.wrapping_add(seed);
        key = (!key << 0x15).wrapping_add(0x1111_1111) | (key >> 0x0B);
        seed = plain
            .wrapping_add(seed)
            .wrapping_add(seed << 5)
            .wrapping_add(3);
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    /// StormLib's canonical vectors — these pin our table + hash to the real client byte-for-byte.
    #[test]
    fn hash_vectors_match_stormlib() {
        assert_eq!(
            hash_string("(hash table)", hash_type::FILE_KEY),
            0xC3AF_3770
        );
        assert_eq!(
            hash_string("(block table)", hash_type::FILE_KEY),
            0xEC83_B3A3
        );
        assert_eq!(
            hash_string("file.txt", hash_type::TABLE_OFFSET),
            0x3EA9_8D7A
        );
    }

    #[test]
    fn hash_is_slash_and_case_insensitive() {
        let a = hash_string("path\\to\\FILE.blp", hash_type::TABLE_OFFSET);
        let b = hash_string("path/to/file.blp", hash_type::TABLE_OFFSET);
        assert_eq!(a, b);
    }

    /// decrypt∘encrypt round-trips (encrypt is the same walk with the xor on the other side).
    #[test]
    fn decrypt_inverts_encrypt() {
        let key = hash_string("(hash table)", hash_type::FILE_KEY);
        let original = [0x1234_5678u32, 0x9ABC_DEF0, 0x0F0F_0F0F, 42];
        let mut buf = original;
        encrypt_block(&mut buf, key);
        decrypt_block(&mut buf, key);
        assert_eq!(buf, original);
    }
}
